// < This File is Auto Generated By EF Core />


using Day_05_Demo.Sealed;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Day_05_Demo.Partial
{
	// Developer 01
	internal partial class Employee : Parent
	{
		public int Id { get; set; }
		public string? Name { get; set; }
		public int? Age { get; set; }


		// Partial Method
		public partial int DoSomeCode(int X);
		public void Test()
		{
			DoSomeCode(10);
		}
	}
}
